.test: &test
  stage: test
  script:
    - export TOXENV=''

test:2.7:
  <<: *test
  script:
    - pip install tox
    - tox -e "py27"
  tags:
    - python27
    - debian-jessie

test:3.5:
  <<: *test
  script:
    - pip3 install tox
    - tox -e "flake8,py35"
  tags:
    - python35
    - debian-stretch

pages:
  stage: deploy
  script:
    - pip3 install -r requirements/dev.txt
    - cd docs
    - make html
    - cd ..
    - mv docs/_build/html/ public
  artifacts:
    paths:
      - public
  tags:
    - python35
    - debian-stretch
  only:
    - development

publish:
  stage: deploy
  script:
    - devpi use $DEVPI_SERVER
    - devpi login --password $DEVPI_PASSWORD $DEVPI_USER
    - devpi upload --no-vcs
    - devpi upload --no-vcs --formats bdist_wheel
  only:
    - tags
  tags:
    - python35
    - debian-stretch

variables:
  PIP_INDEX_URL: "https://devpi.intern.rheinwerk.de/rheinwerk/dev"
  PIP_TRUSTED_HOST: "devpi.intern.rheinwerk.de"
  DEVPI_SERVER: "https://devpi.intern.rheinwerk.de/rheinwerk/prod/+simple/"
  DEVPI_USER: "rheinwerk"
