name: Release

on: [push]

#on:
#  release:
#    types: [created]

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      #name: pypi
      name: testpypi
      url: https://pypi.org/project/pganonymize/
    permissions:
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
