name: Test

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint
      run: tox -e flake8
  tests:
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8', '3.9', '3.10']
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --use-pep517 tox "coverage<5"
    - name: Run tests
      run: |
        export TOXENV=$(echo "py${{ matrix.python-version }}" | sed 's/\.//g')
        tox -- -p no:warnings
    - name: Generate coverage report
      run: coverage xml
      if: ${{ success() }}
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.xml
        if-no-files-found: ignore
      if: ${{ success() }}
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 "coverage<5"
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - run: ls -lh .
      - name: Create HTML report
        run: coverage html
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: htmlcov
          if-no-files-found: ignore
        if: ${{ success() }}
